// IntentX Solana program configuration.
//
// This file is auto-generated by scripts/anchor_deploy.sh after deployment.
// The placeholder values below are overwritten with real program IDs.
// You can also override any value via NEXT_PUBLIC_ env vars.

export const SOLANA_CONFIG = {
  cluster: (process.env.NEXT_PUBLIC_SOLANA_NETWORK || "devnet") as
    | "devnet"
    | "mainnet-beta"
    | "localnet",

  rpcUrl:
    process.env.NEXT_PUBLIC_SOLANA_RPC_URL ||
    "https://api.devnet.solana.com",

  // ── Program IDs ─────────────────────────────────────────
  // Populated by anchor_deploy.sh after deployment.
  // Override via env vars for per-environment configuration.

  settlementProgramId:
    process.env.NEXT_PUBLIC_SETTLEMENT_PROGRAM_ID ||
    "11111111111111111111111111111111",

  htlcProgramId:
    process.env.NEXT_PUBLIC_HTLC_PROGRAM_ID ||
    "HtLc1111111111111111111111111111111111111111",

  // ── Authority ───────────────────────────────────────────
  // Backend signer that executes settlements on-chain.

  authority: process.env.NEXT_PUBLIC_AUTHORITY || "",

  // ── Fee config ──────────────────────────────────────────

  feeBps: parseInt(process.env.NEXT_PUBLIC_FEE_BPS || "10", 10),

  // ── PDA seeds (must match on-chain constants) ───────────

  seeds: {
    config: "config",
    user: "user",
    vault: "vault",
    htlc: "htlc",
    escrow: "escrow",
  },
} as const;

export type SolanaCluster = typeof SOLANA_CONFIG.cluster;
